version: '2'
services:
  code:
    extends:
      file: docker-compose.common.yml
      service: code
  fireworq:
    environment:
      - GOOS
      - GOARCH
      - USER_ID
      - GROUP_ID
    extends:
      file: docker-compose.common.yml
      service: fireworq
    entrypoint: ${FIREWORQ_ROOT}/script/docker/entrypoint.build.sh
    volumes:
      - ../..:/workspace
    volumes_from:
      - code
